package View;

import Model.DAO.AlunoDAO;
import Model.bean.Aluno;
import Model.bean.Pais;
import Model.bean.Turma;
import Tratamento_Exception.TextFieldValidator;
import javax.swing.JOptionPane;

public class Cadastro_Alunos extends javax.swing.JFrame {
    
    TextFieldValidator validator = new TextFieldValidator();
    
    public Cadastro_Alunos() {
        initComponents();
    }
   public Cadastro_Alunos(String login) {
        initComponents();
        Login.setText(login);
        
        jLabelMsg.setVisible(false);
        jLRGMsg.setVisible(false);
        jLCPFMsg.setVisible(false);
        jLEmailMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLRGMsg = new javax.swing.JLabel();
        jLEmailMsg = new javax.swing.JLabel();
        jLabelMsg = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        CPF = new javax.swing.JTextField();
        RG = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Serie = new javax.swing.JTextField();
        Turno = new javax.swing.JTextField();
        Rua = new javax.swing.JTextField();
        Num = new javax.swing.JTextField();
        Pai = new javax.swing.JTextField();
        Mae = new javax.swing.JTextField();
        jLCPFMsg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLLimpar = new javax.swing.JLabel();
        jLCadastrar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCadastrarBtn = new javax.swing.JButton();
        jLimparBtn = new javax.swing.JButton();
        Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLRGMsg.setBackground(new java.awt.Color(241, 196, 15));
        jLRGMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLRGMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLRGMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRGMsg.setText("Somente números!");
        jLRGMsg.setOpaque(true);
        getContentPane().add(jLRGMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 185, 120, -1));

        jLEmailMsg.setBackground(new java.awt.Color(231, 76, 60));
        jLEmailMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLEmailMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLEmailMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEmailMsg.setText("Por favor insira um email válido!");
        jLEmailMsg.setOpaque(true);
        getContentPane().add(jLEmailMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 185, 200, -1));

        jLabelMsg.setBackground(new java.awt.Color(231, 76, 60));
        jLabelMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabelMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMsg.setText("Por favor preencha todos os campos!");
        jLabelMsg.setOpaque(true);
        getContentPane().add(jLabelMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 610, 230, -1));

        Nome.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Nome.setBorder(null);
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomeKeyTyped(evt);
            }
        });
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, 290, -1));

        CPF.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        CPF.setBorder(null);
        CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CPFFocusLost(evt);
            }
        });
        CPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPFKeyTyped(evt);
            }
        });
        getContentPane().add(CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 152, 210, -1));

        RG.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        RG.setBorder(null);
        RG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RGFocusLost(evt);
            }
        });
        RG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RGKeyTyped(evt);
            }
        });
        getContentPane().add(RG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 212, 210, -1));

        Email.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Email.setBorder(null);
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailKeyTyped(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 212, 290, -1));

        Serie.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Serie.setBorder(null);
        getContentPane().add(Serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 273, 39, -1));

        Turno.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Turno.setAlignmentY(0.3F);
        Turno.setBorder(null);
        getContentPane().add(Turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 273, 39, -1));

        Rua.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Rua.setBorder(null);
        Rua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RuaKeyTyped(evt);
            }
        });
        getContentPane().add(Rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 578, 430, -1));

        Num.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Num.setBorder(null);
        Num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumKeyTyped(evt);
            }
        });
        getContentPane().add(Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 578, 70, -1));

        Pai.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Pai.setBorder(null);
        Pai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PaiKeyTyped(evt);
            }
        });
        getContentPane().add(Pai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 394, 530, -1));

        Mae.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Mae.setBorder(null);
        Mae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MaeKeyTyped(evt);
            }
        });
        getContentPane().add(Mae, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 455, 530, -1));

        jLCPFMsg.setBackground(new java.awt.Color(241, 196, 15));
        jLCPFMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLCPFMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLCPFMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCPFMsg.setText("Somente números!");
        jLCPFMsg.setOpaque(true);
        getContentPane().add(jLCPFMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 123, 120, -1));

        jPanel1.setMaximumSize(new java.awt.Dimension(596, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(596, 60));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(596, 60));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLimparMouseClicked(evt);
            }
        });
        jPanel1.add(jLLimpar);

        jLCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCadastrarMouseClicked(evt);
            }
        });
        jPanel1.add(jLCadastrar);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 634, -1, 45));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CadastrarAlunoWindow.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jCadastrarBtn.setBackground(new java.awt.Color(255, 255, 255));
        jCadastrarBtn.setFocusPainted(false);
        jCadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(jCadastrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 280, 36));

        jLimparBtn.setBackground(new java.awt.Color(255, 255, 255));
        jLimparBtn.setFocusPainted(false);
        jLimparBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimparBtnActionPerformed(evt);
            }
        });
        getContentPane().add(jLimparBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 280, 36));

        Login.setText("jLabel1");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 21, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void jLimparBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimparBtnActionPerformed
        
    }//GEN-LAST:event_jLimparBtnActionPerformed

    private void jCadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarBtnActionPerformed
        
    }//GEN-LAST:event_jCadastrarBtnActionPerformed

    private void jLLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLimparMouseClicked
        CPF.setText("");
        Nome.setText("");
        RG.setText("");
        Email.setText("");
        Num.setText("");
        Rua.setText("");
        Mae.setText("");
        Pai.setText("");
        Serie.setText("");
        Turno.setText("");
    }//GEN-LAST:event_jLLimparMouseClicked

    private void jLCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCadastrarMouseClicked
        if(CPF.getText().equals("") || Email.getText().equals("") || Nome.getText().equals("") || RG.getText().equals("")
                || Serie.getText().equals("") || Turno.getText().equals("") || Pai.getText().equals("") || Mae.getText().equals("")
                || Rua.getText().equals("") || Num.getText().equals("")){
            
            jLabelMsg.setVisible(true);
        }else if(!validator.emailValidate(Email)){            
            jLEmailMsg.setVisible(true);      
        }else{
            String User_Login = Login.getText();
            
            AlunoDAO adao = new AlunoDAO();
            Aluno a = new Aluno();
            a.setCPF(CPF.getText());
            a.setRG(RG.getText());
            a.setEmail(Email.getText());
            a.setNome(Nome.getText());
            
            Turma t = new Turma();
            t.setSerie(Serie.getText());
            t.setTurno(Turno.getText());
            
            Pais p = new Pais();
            p.setLogradouro(Rua.getText());
            p.setNome_mae(Mae.getText());
            p.setNome_pai(Pai.getText());
            p.setNum(Num.getText());
            
            if(adao.create(a, t, p, User_Login)){
                JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso");
                jLLimparMouseClicked(evt);
            }
            else{
                JOptionPane.showMessageDialog(null, "Erro ao Cadastrar");
            }
        }
    }//GEN-LAST:event_jLCadastrarMouseClicked

    private void CPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CPFFocusGained
        jLCPFMsg.setVisible(true);        
    }//GEN-LAST:event_CPFFocusGained

    private void RGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RGFocusLost
        jLRGMsg.setVisible(false);
    }//GEN-LAST:event_RGFocusLost

    private void CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CPFFocusLost
        jLCPFMsg.setVisible(false);
    }//GEN-LAST:event_CPFFocusLost

    private void RGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RGFocusGained
        jLRGMsg.setVisible(true);
    }//GEN-LAST:event_RGFocusGained

    private void CPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPFKeyTyped
        validator.numericValidate(evt);
        validator.maxLengthLimit(CPF, 11);
    }//GEN-LAST:event_CPFKeyTyped

    private void RGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RGKeyTyped
        validator.numericValidate(evt);
        validator.maxLengthLimit(RG, 13);
    }//GEN-LAST:event_RGKeyTyped

    private void NomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeKeyTyped
        validator.maxLengthLimit(Nome, 40);
    }//GEN-LAST:event_NomeKeyTyped

    private void EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyTyped
        validator.maxLengthLimit(Email, 30);
    }//GEN-LAST:event_EmailKeyTyped

    private void PaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaiKeyTyped
        validator.maxLengthLimit(Pai, 40);
    }//GEN-LAST:event_PaiKeyTyped

    private void MaeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaeKeyTyped
        validator.maxLengthLimit(Mae, 40);
    }//GEN-LAST:event_MaeKeyTyped

    private void RuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RuaKeyTyped
        validator.maxLengthLimit(Rua, 50);
    }//GEN-LAST:event_RuaKeyTyped

    private void NumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumKeyTyped
        validator.numericValidate(evt);
        validator.maxLengthLimit(Num, 4);
    }//GEN-LAST:event_NumKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Cadastro_Alunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPF;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Login;
    private javax.swing.JTextField Mae;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Num;
    private javax.swing.JTextField Pai;
    private javax.swing.JTextField RG;
    private javax.swing.JTextField Rua;
    private javax.swing.JTextField Serie;
    private javax.swing.JTextField Turno;
    private javax.swing.JButton jCadastrarBtn;
    private javax.swing.JLabel jLCPFMsg;
    private javax.swing.JLabel jLCadastrar;
    private javax.swing.JLabel jLEmailMsg;
    private javax.swing.JLabel jLLimpar;
    private javax.swing.JLabel jLRGMsg;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JButton jLimparBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
