package View;

import Model.DAO.UsuarioDAO;
import Model.bean.Usuario;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class LoginWindow extends javax.swing.JFrame {
    
    private int mouseX = 0;
    private int mouseY = 0;
    
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLEntrarBtn = new javax.swing.JLabel();
        jLabelBG = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login no Sistema");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(346, 460));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMinimize.setToolTipText("Minimizar");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 22, 20, 20));

        jLabelClose.setToolTipText("Fechar");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 22, 20, 20));

        jTFUsuario.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jTFUsuario.setForeground(new java.awt.Color(137, 148, 154));
        jTFUsuario.setBorder(null);
        jTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 270, 30));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(137, 148, 154));
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 326, 270, 30));

        jLEntrarBtn.setBackground(new java.awt.Color(255, 255, 255));
        jLEntrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLEntrarBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLEntrarBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLEntrarBtnMouseReleased(evt);
            }
        });
        getContentPane().add(jLEntrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 290, 50));

        jLabelBG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loginWindow.png"))); // NOI18N
        jLabelBG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelBGMouseDragged(evt);
            }
        });
        jLabelBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBGMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelBGMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 460));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBGMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
        jLabelBG.setCursor(new Cursor(java.awt.Cursor.MOVE_CURSOR));
    }//GEN-LAST:event_jLabelBGMousePressed

    private void jLabelBGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBGMouseDragged
        this.setLocation(evt.getXOnScreen() - mouseX, evt.getYOnScreen() - mouseY);
    }//GEN-LAST:event_jLabelBGMouseDragged

    private void jLabelBGMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBGMouseReleased
        jLabelBG.setCursor(new Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabelBGMouseReleased

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setState(LoginWindow.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void jLEntrarBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEntrarBtnMousePressed
        jLEntrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/btnPressed.png")));
    }//GEN-LAST:event_jLEntrarBtnMousePressed

    private void jLEntrarBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEntrarBtnMouseReleased
        jLEntrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
    }//GEN-LAST:event_jLEntrarBtnMouseReleased

    private void jLEntrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEntrarBtnMouseClicked
        String login = jTFUsuario.getText();
        String senha = jPasswordField1.getText();
        
        Usuario usu = new Usuario();
        UsuarioDAO udao = new UsuarioDAO();
        usu.setLogin(login);
        usu.setSenha(senha);
        
        if(udao.efetuarLogin(usu)){
            switch (usu.getTipo_user()) {
                case "1": // Tela administrador
                    PrincipalWindow admin = new PrincipalWindow(usu);
                    admin.setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Login feito com Sucesso");
                    break;
                case "2": // Tela Funcionario
                    PrincipalWindow func = new PrincipalWindow(usu);
                    func.setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Login feito com Sucesso");
                    break;
                case "3": // Tela Professor
                    PrincipalWindow prof = new PrincipalWindow(usu);
                    prof.setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Login feito com Sucesso");
                    break;
                default:
                    break;
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Login e/ou Senha Incorretos");
        }
            
    }//GEN-LAST:event_jLEntrarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEntrarBtn;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
