package View;


import Model.DAO.NotaDAO;
import Model.bean.Aluno;
import Model.bean.Disciplina;
import Model.bean.Nota;
import Model.bean.Turma;
import Model.bean.Usuario;
import Tratamento_Exception.TextFieldValidator;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Notas extends javax.swing.JFrame {
    
    TextFieldValidator validator = new TextFieldValidator();
    private Usuario u;
    private Turma t ;
    private Aluno a ;
    private Nota n;
    private List<Nota> listNota = null;
    private int muda = 1;
    
    public Notas() {
        initComponents();
      
    }
    
    public Notas(Aluno a, Usuario u, Turma t) {
        initComponents();
        this.a = a;
        this.u = u;
        this.t = t;
        loadNotasJTable();
        jLabelMsg.setVisible(false);
        jAlunoLabel.setText("Aluno: "+this.a.getNome());
        jProfessorLabel.setText("Professor: "+this.u.getNome());
        jTurmaLabel.setText("Série: "+this.t.getSerie());
        jDisciplinaLabel.setText("Disciplina: "+this.t.getDisc_nome());
        jTunoLabel.setText("Turno: "+this.t.getTurno());
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProfessorLabel = new javax.swing.JLabel();
        jTurmaLabel = new javax.swing.JLabel();
        jDisciplinaLabel = new javax.swing.JLabel();
        jAlunoLabel = new javax.swing.JLabel();
        jTunoLabel = new javax.swing.JLabel();
        jTipoTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jValorTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBimestreTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNotas = new javax.swing.JTable();
        jEditarBtn = new javax.swing.JButton();
        jDeletarBtn = new javax.swing.JButton();
        jCadastrarBtn1 = new javax.swing.JButton();
        jLabelMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jProfessorLabel.setText("PROFESSOR:");

        jTurmaLabel.setText("TURMA:");

        jDisciplinaLabel.setText("DISCIP:");

        jAlunoLabel.setText("ALUNO:");

        jTunoLabel.setText("TURNO:");

        jTipoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoTfActionPerformed(evt);
            }
        });
        jTipoTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTipoTfKeyPressed(evt);
            }
        });

        jLabel2.setText("TIPO:");

        jLabel3.setText("VALOR:");

        jValorTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorTfActionPerformed(evt);
            }
        });
        jValorTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jValorTfKeyPressed(evt);
            }
        });

        jLabel4.setText("BIMESTRE:");

        jBimestreTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimestreTfActionPerformed(evt);
            }
        });
        jBimestreTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBimestreTfKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTurmaLabel)
                            .addComponent(jTunoLabel))
                        .addGap(0, 163, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAlunoLabel)
                            .addComponent(jDisciplinaLabel))
                        .addGap(125, 125, 125)
                        .addComponent(jProfessorLabel)
                        .addGap(122, 122, 122))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTipoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jValorTf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jBimestreTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTunoLabel)
                    .addComponent(jDisciplinaLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTurmaLabel)
                    .addComponent(jAlunoLabel)
                    .addComponent(jProfessorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBimestreTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jValorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTipoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Bimestre", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNotas);

        jEditarBtn.setText("EDITAR");
        jEditarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarBtnActionPerformed(evt);
            }
        });

        jDeletarBtn.setText("DELETAR");
        jDeletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeletarBtnActionPerformed(evt);
            }
        });

        jCadastrarBtn1.setText("SALVAR");
        jCadastrarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarBtn1ActionPerformed(evt);
            }
        });

        jLabelMsg.setBackground(new java.awt.Color(231, 76, 60));
        jLabelMsg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabelMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMsg.setText("Por favor preencha todos os campos!");
        jLabelMsg.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCadastrarBtn1)
                        .addGap(60, 60, 60)
                        .addComponent(jEditarBtn)
                        .addGap(51, 51, 51)
                        .addComponent(jDeletarBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditarBtn)
                    .addComponent(jDeletarBtn)
                    .addComponent(jCadastrarBtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabelMsg)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValorTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorTfActionPerformed

    private void jBimestreTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimestreTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBimestreTfActionPerformed

    private void jTipoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTipoTfActionPerformed

    private void jEditarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarBtnActionPerformed
        int selIndex = jTableNotas.getSelectedRow();        
        
        if(selIndex>=0){
            muda = 2;
            n = (Nota) listNota.get(selIndex);
            jTipoTf.setText(n.getDescricao());
            jValorTf.setText(Float.toString(n.getValor()));
            jBimestreTf.setText(n.getBimestre());
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma nota na tabela a ser alterada");   
        }
    }//GEN-LAST:event_jEditarBtnActionPerformed

    private void jDeletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeletarBtnActionPerformed
        int selIndex = jTableNotas.getSelectedRow();        
        
        if(selIndex>=0){
            n = (Nota) listNota.get(selIndex);
            NotaDAO ndao = new NotaDAO();
            
            if(ndao.DeleteNotas(n, u.getUser_id())){
                JOptionPane.showMessageDialog(null, "Nota Deletada com Sucesso"); 
            }
            else{
                JOptionPane.showMessageDialog(null, "Erro ao Excluir Nota"); 
            }     
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma nota na tabela a ser Excluida");   
        }
    }//GEN-LAST:event_jDeletarBtnActionPerformed

    private void jCadastrarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarBtn1ActionPerformed
        
        if(muda==1){
            if(jTipoTf.getText().equals("") || jValorTf.getText().equals("") 
                    || jBimestreTf.getText().equals("")){

                jLabelMsg.setText("Preencha todos os campos");
                jLabelMsg.setVisible(true);
            }
            else{
                jLabelMsg.setVisible(false);
                Nota no = new Nota();
                NotaDAO ndao = new NotaDAO();

                no.setBimestre(jBimestreTf.getText());
                no.setDescricao(jTipoTf.getText());
                no.setValor(Float.parseFloat(jValorTf.getText()));

                Disciplina d = new Disciplina();
                d.setDisc_id(t.getId_disc());

                if(ndao.create(no, a, d, u.getLogin())){
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso");
                    jLLimparBtnMouseClicked(evt);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Cadastro Não Realizado");
                }

            }
        }
        else{
            n.setBimestre(jBimestreTf.getText());
            n.setDescricao(jTipoTf.getText());
            n.setValor(Float.parseFloat(jValorTf.getText()));

            NotaDAO  ndao = new NotaDAO();

            if(ndao.UpdateNotas(n)){
                JOptionPane.showMessageDialog(null, "Nota Alterada com Sucesso");  
            }
            else{
                JOptionPane.showMessageDialog(null, "Erro ao Alterar Nota");   
            }
        }
    }//GEN-LAST:event_jCadastrarBtn1ActionPerformed

    private void jLLimparBtnMouseClicked(ActionEvent evt) {
        jTipoTf.setText("");
        jValorTf.setText("");
        jBimestreTf.setText("");
    }
    private void jTipoTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTipoTfKeyPressed
        validator.maxLengthLimit(jTipoTf, 25);
    }//GEN-LAST:event_jTipoTfKeyPressed

    private void jValorTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValorTfKeyPressed
        validator.maxLengthLimit(jValorTf, 4);
    }//GEN-LAST:event_jValorTfKeyPressed

    private void jBimestreTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBimestreTfKeyPressed
        validator.maxLengthLimit(jBimestreTf, 1);
    }//GEN-LAST:event_jBimestreTfKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadNotasJTable();
    }//GEN-LAST:event_formWindowActivated
    private void loadNotasJTable(){
        DefaultTableModel model = (DefaultTableModel) jTableNotas.getModel();
        model.setNumRows(0);
        NotaDAO notaDAO = new NotaDAO();                                             
        listNota = notaDAO.ListNotas(a.getMatricula(), t.getId_disc());
    
        listNota.stream().forEach((n) -> {
            model.addRow(new Object[]{
                n.getDescricao(),
                n.getBimestre(),
                n.getValor()
            });
        });   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAlunoLabel;
    private javax.swing.JTextField jBimestreTf;
    private javax.swing.JButton jCadastrarBtn1;
    private javax.swing.JButton jDeletarBtn;
    private javax.swing.JLabel jDisciplinaLabel;
    private javax.swing.JButton jEditarBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jProfessorLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNotas;
    private javax.swing.JTextField jTipoTf;
    private javax.swing.JLabel jTunoLabel;
    private javax.swing.JLabel jTurmaLabel;
    private javax.swing.JTextField jValorTf;
    // End of variables declaration//GEN-END:variables
}
